### PR TITLE
Added proxy setting for speech_to_text WebSockets

### PR DESCRIPTION
**Pull request by Omegastick**

### CODE REVIEW

**Comment by germanattanasio** [comment]
Hey @Omegastick you need to sign the commit and probably add a test before we can merge this. Check your git configuration

**Comment by Omegastick** [comment]
I think I fixed the username problem.

I'm having trouble adding a test because there's no mock library for your WebSocket implementation (as far as I can see). I'd have to add another dependency. Any suggestions?

By the way, as mentioned in #402, this doesn't actually work for me. The bug I was getting before is still there.

**Comment by germanattanasio** [comment]
We currently have a way to setup the http configuration parameters. See https://github.com/watson-developer-cloud/python-sdk#configuring-the-http-client-supported-from-v110

I would like to use the parameters there instead of asking the user for the proxy host and port again.

**Comment by Omegastick** [comment]
Would you like me to add a `set_websocket_config` method?

**Comment by germanattanasio** [comment]
I think we can add a `service.set_websocket_config({'proxy': { ... } })`

**Comment by Omegastick** [comment]
Sorry for the delay, work has been busy lately. I'll get around to this this week I think.

**Comment by ehdsouza** [comment]
Closing this as we would be looking into a new web socket library

**Pull request closed without merging**
