### PR TITLE
Adding example script for running learning-to-rank experiments

### PR DESCRIPTION
**Pull request by rchaks**
Demonstrate use of the /rank API methods (part of the Retrieve and Rank service) using a command line runnable script for learning-to-rank experiments.  Blog containing detailed experimental usage of the script to follow once code becomes available in the public repo.

### CODE REVIEW

**Comment by rchaks** [comment]
@germanattanasio - Do we need to check in unit tests for example scripts (there didn't seem to be any for previous example scripts)?  If so, are there prior examples scripts I could take a look at?  Specifically, I would like to figure out how to mock out the REST calls (my local unit tests required a valid set of credentials that could be used to call the RnR service).

**Comment by germanattanasio** [comment]
Python is pretty flexible, if you look at our tests we use `responses` so you can mock the API and call your script using `os.processor` like if it was a script call

**Comment by jsstylos** [comment]
I added the file in a folder called `utilities` in 302c9b588610536ec99f6c6673799c3d68789cdb

**Comment by rchaks** [comment]
@jsstylos - thanks for pulling that in!  One note: I saw that you re-named it a **retrieve-and-**rank utility.  However, the utility only really allows the user to use the **rank** api methods.  The goal being to show the use of the learning-to-rank as a standalone algorithm for solving non-retrieval tasks (blog upcoming with real example that uses the script).

**Comment by jsstylos** [comment]
@rchaks: The naming is intended to show the service that is used, not imply that it's using all of the capabilities of the service; just calling it rank didn't make it clear which Developer Cloud service it is using. I imagine that a speech utility would be speech_to_text_v1_websockets.py or something, even if it wasn't using all of the capabilities of the Speech to Text service, and we might have separate speech_to_text_v1_customization.py and retrieve_and_rank_v1_retrieve.py utilities. An alternative design would be to create a folder to act as namespace, /utilities/retrieve_and_rank_v1/rank.py

**Pull request closed without merging**
