### PR TITLE
adds (some) unit tests for alchemy language

### PR DESCRIPTION
**Pull request by kognate**
This adds some unit tests

### CODE REVIEW

**Comment by jsstylos** [comment]
Do we need sudo and pypandoc on Travis? Right now it's only used when publishing, which Travis doesn't currently need to do.

**Comment by kognate** [comment]
The builds failed without it when it did the `python setup.py egg_info` step

**Comment by jsstylos** [comment]
I think that was due to a related issue that was fixed in https://github.com/watson-developer-cloud/python-sdk/pull/132 without sudo or pypandoc -- the builds are working now.

**Comment by kognate** [comment]
replaced with #133

**Pull request closed without merging**
