### PR TITLE
Fix PersonalityInsightsV3 problem "accept:text/csv" is not reflected

### PR DESCRIPTION
**Pull request by birdtomita**
Please Merge this,
fix Personality Insights parameter "accept" was not reflected

### CODE REVIEW

**Comment by birdtomita** [comment]
I just signed CLA.


2018-01-23 10:46 GMT+09:00 CLAassistant <notifications@github.com>:

**Comment by germanattanasio** [comment]
Thanks for the PR @birdtomita! It looks good.
Can you add a unit test validating that the header is part of the request now?
There are a few examples in the code so it should be easy but let us know if you need help.

**Comment by birdtomita** [comment]
I have to write a test code! I forgot. I will update it around 10 hours
later because it is already midnight in Japan.
2018年1月23日(火) 23:25 German Attanasio <notifications@github.com>:

**Comment by birdtomita** [comment]
I was watching the source trying to write the test code, but is the test
code called test_json_to_csv () wrong?
Can I modify this?
A method for CSV validation could not be found in this library, but is it
somewhere?

2018-01-23 23:33 GMT+09:00 Bird Tomita <bird.tomita@gmail.com>:

**Comment by germanattanasio** [comment]
@birdtomita sorry for the delay we will try to get to this PR this week

**Comment by birdtomita** [comment]
thanks

2018-02-03 6:14 GMT+09:00 German Attanasio <notifications@github.com>:

**Pull request merged**
