### PR TITLE
Add Conversation intents, examples, and counterexamples

### LINKED ISSUE #181: Add Intents, Examples and Counterexamples to Conversation SDK
The API has been updated early February and not all features are supported by the Python SDK.

https://www.ibm.com/watson/developercloud/conversation/api/v1/#versioning

### PR DESCRIPTION
**Pull request by glennrfisher**
## Overview

This pull request adds support for the Conversation service's intent, examples, and counterexamples operations. Closes #181.

## Details

Most of the code was generated using `WatsonPythonCodegen`, although some manual changes were necessary (see 7219670ca53567f42d6658f518d1237b701dac71 for `conversation_v1.py` and 69e064932f896654b99bd82ccf5b1b701b00601d for `test_conversation_v1.py`).

A few notes that I'd like to draw your attention to:
- I used [YAPF][1] to automatically format the code. I also tried to make additional changes to adhere to the SDK's existing style. Let me know if there are any formatting changes I should make.
- There were naming conflicts between a path parameter and body variable for the `update_counterexample`, `update_intent`, and `update_example` operations. To resolve the conflict, I prefixed the body variables with `new_`.
- The unit tests follow the existing convention of verifying the URL and response object. Let me know if I should additional tests or assert statements.

## Tests

The unit tests pass on my machine:

```
(watson-python-sdk) Glenns-MacBook-Pro:test glennrfisher$ py.test test_conversation_v1.py
================================================= test session starts ==================================================
platform darwin -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /Users/glennrfisher/Repositories/python-sdk, inifile:
plugins: cov-2.4.0
collected 21 items

test_conversation_v1.py .....................

============================================== 21 passed in 0.16 seconds ===============================================
```

The example also passes on my machine:

```
(watson-python-sdk) Glenns-MacBook-Pro:examples glennrfisher$ python conversation_v1.py
{
  "intents": [
    {
      "intent": "weather",
      "confidence": 0.9986543028393314
    }
  ],
  "entities": [],
  "input": {
    "text": "What's the weather like?"
  },
  "output": {
    "log_messages": [],
    "text": [
      "Hi. It looks like a nice drive today. What would you like me to do?"
    ],
    "nodes_visited": [
      "node_1_1467221909631"
    ]
  },
  "context": {
    "conversation_id": "31998782-8ef1-4002-a9e1-e8c4c4436d00",
    "system": {
      "dialog_stack": [
        {
          "dialog_node": "root"
        }
      ],
      "dialog_turn_counter": 1,
      "dialog_request_counter": 1,
      "branch_exited": true,
      "branch_exited_reason": "completed"
    },
    "defaultCounter": 0
  }
}
```

[1]: https://github.com/google/yapf

### CODE REVIEW

**Comment by germanattanasio** [comment]
@jsstylos can you take a look at this?

**Comment by germanattanasio** [comment]
The code looks good and I love that we can generate the documentation for each method.
@glennrfisher did you do some sort of integration tests for all the methods?

**Comment by germanattanasio** [comment]
There are some code style issues.

You can see them by running `sh pylint.sh`

**Comment by germanattanasio** [comment]
The errors are not in your code. We merged code that has lint issues...

**Comment by jsstylos** [comment]
I think there's still one issue to be resolved around parameter ordering.

**Comment by glennrfisher** [comment]
There was an issue with the order of `metadata` that would cause a breaking change.

Mike and I were looking to see if we could rearrange the order of parameters in the Swagger to generate a fix. But I'll make a quick PR by hand to prevent that bug from lingering in the `master` branch for too long.

**Comment by germanattanasio** [comment]
I left the PR open for 2 days but since I didn't see any comment I went ahead and merged it.  I forgot about the ordering issue

**Pull request merged**
