### PR TITLE
First whack at v3 image recognition

### LINKED ISSUE #60: Support for Visual Recognition V3?
When will the SDK be updated for v3?

Also there seems to be sample python code missing from the documentation:
http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/visual-recognition/api/v3/?python#recognize_text

### PR DESCRIPTION
**Pull request by kognate**
This adds the v3 image recognition for python.  This includes
multi-class classifier, face detection, and text recognition.

fixes #60

### CODE REVIEW

**Comment by germanattanasio** [comment]
@kognate: looks like you have some PEP8 issues.

You need to make `pylint` happy 💃 
```
$ sh pylint.sh
```

**Comment by jsstylos** [comment]
Very nice! I fixed the PEP8 issues but haven't been able to get the POST based image uploads to work (the url-based ones work fine).

**Comment by jsstylos** [comment]
You can see the changes I made at: https://github.com/watson-developer-cloud/python-sdk/tree/visual-recognition-v3

**Comment by kognate** [comment]
I'll more tests and make sure it all works the way it supposed to.

**Comment by kognate** [comment]
OK,  the PEP8 issues have been fixed and the codecov has been appeased.   The VR service needs the content type of posted images to be set correctly (not just octet stream, which I've updated).

**Comment by kognate** [comment]
This was superseded by another PR.

**Pull request closed without merging**
