### PR TITLE
x_watson_learning_opt_out for natural language understanding

### PR DESCRIPTION
**Pull request by samuel500**

### CODE REVIEW

**Comment by samuel500** [comment]
Is the fact that it failed with Python 2.7 actually an issue?

**Comment by germanattanasio** [comment]
Hi @samuel500, What's the idea behind this pull requests? 
Travis fails because of  pylint issues
```none
** Module watson_developer_cloud.natural_language_understanding_v1
C: 39, 0: No space allowed around keyword argument assignment
            x_watson_learning_opt_out = x_watson_learning_opt_out)
                                      ^ (bad-whitespace)
```

Once you fix the whitespace issue run `sh pylint.sh` to verify that the code passes the code style rules

**Comment by samuel500** [comment]
Ok, fixed the pylint issue. 
The idea behind the pull request is to make it possible to opt out of Watson learning while using natural language understanding. For the service I'm building I need to give the option to users that the data they provide will not be used in any way. That is not possible right now using natural_language_understanding_v1.py.

**Comment by samuel500** [comment]
Here's the documentation that is inaccurate without my pull:
https://www.ibm.com/watson/developercloud/natural-language-understanding/api/v1/?python#data-collection

**Pull request merged**
