### PR TITLE
Uniform request handling

### PR DESCRIPTION
**Pull request by justinas-vd**
Allow self.request to return an async coroutine, which then can be awaited.

Nota bene: none of these changes expose requests interface, since all of the update methods actually return a JSON dict. Moreover, it is unclear why this dict should not be returned in the sync case.

### CODE REVIEW

**Comment by germanattanasio** [comment]
@justinas-vd we are not going to return the response object since it will expose our underlying library. We have introduced a `DetailedResponse` that you can see as an interface to access the response without exposing `requests` maybe we can update that class to expose the async information you need.

**Comment by justinas-vd** [comment]
First, **None of the changes expose the underlying library.**

This is precisely because the `self.request` method does not return a request object (to which you object, pardon the pun) when `accept_json=True ` is specified. In that case it simply returns a parsed JSON dictionary.

So if you wanted to say that something is "exposed", then the only thing is exposed is a JSON dictionary. Which, by the way, should be exposed. Why on Earth I cannot inspect a JSON response from a Watson service -- I have no idea. I am quite sure, though, that the devs should not prevent me from doing that.


Second, **DetailedResponse does not help if you don't return it.**

When you explicitly return `None` from your API functions, I can have neither detailed responses, nor async coroutine handles upon which I could `await`.

To put it bluntly: fix that brain damage with "return None". It was simply an ill-conceived idea.

**Comment by germanattanasio** [comment]
@justinas-vd The `DetailedResponse` is not returned unless you specify that you want it with `set_detailed_response(True)`

I just went to see what `response = self.request()` was doing and you are right about the dictionary. I thought it was the response from `request()` but that's because we are calling the method `request()` 🤦‍♂️ 

I think we can do this because currently the method ALWAYS returns None, so I don't expect people are writing code based on the response.

Please give me a few days so that I can ask someone else before merging this. We will also have to update a template we use internally to generate the code so that we don't override this manual change.

**Comment by justinas-vd** [comment]
Thank you. I will also update unit tests so that travis does not complain.

**Comment by mkistler** [comment]
There is definitely a problem here, though it’s a bit more complicated than what you suggest.

1.  It does appear that we are not returning a `DetailedReponse` object back on `DELETE`s when detailed responses have been requested, and that is broken.  We need to fix that.
2. When `detailedResponse` is _not_ set, we should continue returning `None`.  We probably have to do that in the method itself, with logic something like
    ```
    response = self.request( ...
    return response if self.detailed_response else None
    ```

3. The `:rtype:`  in the doc comments all need to be fixed.  It should either be
`:rtype: Union[None, DetailedResponse]`
or
`:rtype: Union[dict, DetailedResponse]`

And of course, we need to fix the generator to do this the right way for the next time we generate the Python SDK.

**Comment by justinas-vd** [comment]
Nope. No "None", thank you. This "None" gives only problems and solves absolutely nothing.

Even your suggestion to return None when `DetailedResponse` is not requested is kinda kludgy. Why would one want to write `return response if self.detailed_response else None` in literally dozens of places?

Also, why as a library user I cannot get the JSON from Watson services? I want to see if my request to delete a NLC instance is successful, I want to be able to verify that I deleted a synonym or whatnot. This artificial `return of None` unnecessarily (and for ideological reasons) limits the Python API. It is my discretion -- as a user's -- to ignore what Watson services say back when I delete or put something. Not yours.

**Comment by jsstylos** [comment]
I support moving from `None` to `{}` for the sake of consistency and evolvability. (The initial design did just this.)

Shouldn't changing it back be considered a breaking change, given that users may have their own tests / etc. that check for `None` with the current version?

**Comment by justinas-vd** [comment]
Most likely it won't be a breaking change. A breaking change was introduced with returning `None`. I was almost apoplectic when I got this "new and improved" version. It broke my own project at IBM, and currently I have to duplicate the deletion code.

**Comment by jsstylos** [comment]
As your experience shows, changing the response type can definitely break code. The question here is whether changing it back will break more people who have already written new code, or break more people who haven't yet adapted to the new code.

**Comment by justinas-vd** [comment]
I agree with your concern but I will note this:

1) it's not possible to recover the needed value when you return None;

2) it's quite possible to comment out the assert if you expected None and now you get something more.

So in that regard the breakages are not all equal. The first kind if much much worse than the second.

**Comment by ehdsouza** [comment]
HI @justinas-vd, thanks a lot for your PR. We have an issue created internally to support uniform request handling along with generator changes. 
Also, this would be a breaking change as the `DELETE` response is now changed from `None` to `{}`

**Comment by mkistler** [comment]
@justinas-vd, when we fix the `detailedResponse` logic, the SDK will return a `DetailedResponse` from _every_ service call when `detailedResponse` is set.  Will this be sufficient for your needs?

**Comment by justinas-vd** [comment]
@mkistler   If I understand the vision that you have laid out in README correctly, then the answer would be a "yes".

My requirement is simple: every service call must return a "response" from `self.request` (be it a `{}`, a `DetailedResponse` -- I don't really care). Essentially, I need to use that response to piggyback my async coroutines. (Which I absolutely cannot do when you plainly return `None` and thus discard the result from `self.request`.)

BTW, this PR adresses exactly that and the patched functions would return `DetailedResponse`, too, when you update `self.request`.

**Comment by ehdsouza** [comment]
@justinas-vd thanks for taking the time for making the change.
We now have it in the latest `v2.0.0` release. Check the https://github.com/watson-developer-cloud/python-sdk/wiki/Migration for details

**Comment by justinas-vd** [comment]
@ehdsouza Excellent news. Thank you.

**Pull request closed without merging**
