### PR TITLE
adds similar search, tests and an exmaple for sim search

### LINKED ISSUE #108: Support Visual Recognition similarity search

### PR DESCRIPTION
**Pull request by kognate**
Fixes #108

### CODE REVIEW

**Comment by jsstylos** [comment]
When I try to run `print(json.dumps(visual_recognition.create_collection('test_collection'), indent=2))` I get:
```
/Users/jsstylos/.pyenv/versions/2.7.10/bin/python /Users/jsstylos/code/python-sdk/examples/visual_recognition_v3.py
Traceback (most recent call last):
  File "/Users/jsstylos/code/python-sdk/examples/visual_recognition_v3.py", line 42, in <module>
    print(json.dumps(visual_recognition.create_collection('test_collection'), indent=2))
  File "/Users/jsstylos/code/python-sdk/watson_developer_cloud/visual_recognition_v3.py", line 163, in create_collection
    accept_json=True)
  File "/Users/jsstylos/code/python-sdk/watson_developer_cloud/watson_developer_cloud_service.py", line 290, in request
    raise WatsonException(error_message)
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Error: Error parsing form data: request Content-Type isn't multipart/form-data, Code: 400

Process finished with exit code 1
```

I think this is an oddity about the exact multi-part format accepted by the API that we were able to get around in the other SDKs.

**Comment by kognate** [comment]
I will check that out.

**Comment by jsstylos** [comment]
The unit tests are good -- it's nice to also have integration tests in the examples file (commented out if they're creating or deleting resources) to make sure that each of the endpoints works.

**Comment by kognate** [comment]
I'm writing those now.

**Pull request merged**
