### PR TITLE
stdin speech to text

### PR DESCRIPTION
**Pull request by Fenyx4**
usage
curl -sS http://<streaming-audio-url> | python stdin-speech-to-text.py

First off I'm not a python dev so I'm sorry if I screwed something basic or obvious up.

These libraries and examples helped me a ton and getting it working in stdin was very hard for me. So I wanted to give back by providing it as an example.

### CODE REVIEW

**Comment by Fenyx4** [comment]
Done!
Sorry @mamoonraja didn't see that there.

**Comment by Fenyx4** [comment]
Pssst... Anything you still need from me?

**Comment by mamoonraja** [comment]
@Fenyx4 Thanks for opening the PR, apologies for the delayed response. I like the example, but I am worried about long term support in case people start filing bug cases with us.

**Comment by Fenyx4** [comment]
No worries. 
I find this very useful as it allows it to be easily plug and playable with the rest of the linux ecosystem. 
But I totally understand not wanting to increase your support footprint.

Feel free to close the PR.

**Pull request closed without merging**
