### PR TITLE
python-sdk:  Fix STT test failure and add PI linebreaks.

### PR DESCRIPTION
**Pull request by jeffpk62**
Change False to false in test_speech_to_text_v1.py to pass py.test.
Change linebreaks in personality_insights_v3.py for readability in narrow columns.

### CODE REVIEW

**Comment by jeffpk62** [comment]
@jsstylos @germanattanasio Fixing the help text by removing all remaining embedded linebreaks in params.  Sorry, my latest cleanup didn't completely fix the doc; this one should.

**Comment by jsstylos** [comment]
@jeffpk62 : Can you have the docstring lines wrap to 120 chars also?

**Comment by jeffpk62** [comment]
That broke the formatting, Jeff.  If I embed linebreaks in the param and results lines, the formatting breaks on the first embedded linebreak.  That's why I removed them.

**Comment by jsstylos** [comment]
Broke the formatting where? In PyCharm the doc strings are still formatted correctly with line-breaks, but complains about long lines without them. We should have some strategy for dealing with multi-line doc-streaming comments without needing long lines.

**Comment by jeffpk62** [comment]
When I accessed the help for the build in a browser, embedded linebreaks broke the formatting.  Everything after the linebreak was a Ulyesses-like stream of consciousness on a single line.  Once I removed the embedded linebreaks from the doc comments in the source files, the help text in the build looked fine.

**Comment by jsstylos** [comment]
I think backslashes should keep the source clean while still rendering in one line in the docs: http://stackoverflow.com/questions/32566466/multi-line-description-of-a-parameter-description-in-python-docstring

**Comment by jeffpk62** [comment]
Sorry, it took me a few commits and subsequent builds to understand how the doc strings were working, and I didn't want to risk having to send you guys yet another merge.  I'll clean these up for you with backslashes.

**Comment by jsstylos** [comment]
Cool, thanks.

**Comment by jeffpk62** [comment]
I opened a PR with the changes, Jeff.

**Comment by jsstylos** [comment]
Merged. Might have to wait until the next release to verify that they render correctly, though.

**Pull request merged**
