### PR TITLE
adds custom word customizations

### PR DESCRIPTION
**Pull request by kognate**
Final PR in the fixing the #551 issue

### CODE REVIEW

**Comment by jsstylos** [comment]
Looks like Pylint warnings

**Comment by jsstylos** [comment]
Should `list_custom_word` be `get_custom_word` or something else? I don't think we usually use list for retrieving one item.

**Comment by kognate** [comment]
I was naming it to track with the api nomenclature.  The use 'list a custom word' and 'list custom words' to describe each api endpoint.   Change it to `get`?

**Comment by jsstylos** [comment]
Yeah, I think change to get

**Pull request merged**
