### PR TITLE
added support for pagination for the Watson News Data api.

### PR DESCRIPTION
**Pull request by jtreleaven**
Added a next_page parameter to allow for pagination to work with minimal changes to the get_news_documents function. This PR is in response to the issue I created about the lack pagination support #53.

### CODE REVIEW

**Comment by jsstylos** [comment]
Good catch!

Can you add the field like the other params (without checking to see if it's a string type, since it already gets run through a "remove none" step):

```        params = {'start': start,
                  'end': end,
                  'maxResults': max_results,
                  'return': return_fields,
                  'timeSlice': time_slice,
                  'next': next_page}```

**Comment by jtreleaven** [comment]
Sure thing! I forgot the html_request_method striped out none values!

**Comment by jsstylos** [comment]
What parameter values for the `query_fields` array are the latest changes made to support? From the API reference at https://alchemyapi.readme.io/v1.0/docs/rest-api-documentation it wasn't clear to me that all of the q. prefixed parameters would be limited to the q.enriched.url and q.original.url, or that there were additional non-q.-prefixed parameters other than outputMode, start, end, timeSlice and maxResults.

The `key.startswith('enriched.url') or ...` makes the `if key.startswith('q.')` check unnecessary, if we do want to switch to code to only prefix q. for the enriched.url.* and original.url.* parameters.

**Comment by jsstylos** [comment]
Ok, I found https://github.com/watson-developer-cloud/python-sdk/issues/55 with examples of `dedup` and `dedupThreshold`. I'm still not sure if the right solution is to add optional solution is to add optional fields for `dedup` and `dedupThreshold` and leave `query_fields` specifically for the `q.` query parameters or not.

**Comment by jtreleaven** [comment]
I agree! I wasn't quite sure what to do about the growing number of non 'q.' prefixed fields.
What do you think about creating an option_fields parameter that can contain non 'q.' prefixed url params?

**Comment by jsstylos** [comment]
I'm not sure about what the best way to support additional non-q. fields is. On the one hand they're not unbounded (like the q. fields are), but still numerous, and hard to track down since they're not all documented in one place.

Having a catch-all "option_fields" would be one solution (and is similar to the approach taken in the Java SDK), although it makes discovery more difficult for any fields that aren't also called out as explicit stand-alone parameters. Using `**kwargs` would be a Python specific way, although it has some of the same issues.

For now I added explicit parameters for `dedup`, `dedupThreshold` and `rank`, leaving the `query_fields` specifically for the `q.` parameters`.

**Comment by jsstylos** [comment]
I added the code in 302c9b588610536ec99f6c6673799c3d68789cdb

**Comment by jtreleaven** [comment]
Looks good to me! Thanks for the quick responses and help!

**Pull request closed without merging**
