### PR TITLE
chore: update CHANGELOG

### PR DESCRIPTION
**Pull request by apaparazzi0329**

### CODE REVIEW

**Review by kevinkowa — APPROVED** [review]
Looks good, but should we emphasize the changes more? I believe the java sdk looks like this, but we want to add another line explaining the "breaking changes"

**Comment by apaparazzi0329** [comment]
In that sense, I think every bug fix would be considered a "breaking change" since users will have to change their code to address the fix. Since these are listed as bug fixes though I don't think we need to specify that they are breaking changes as well

**Comment by apaparazzi0329** [comment]
A user will still be able to come to the changelog and see the comment that relates to their error and be able to look at the commit change to figure out what they need to do

**Comment by kevinkowa** [comment]
Alright, that's fine 👍

**Pull request merged**
