### PR TITLE
Now a document can be added from a string

### LINKED ISSUE #140: WDS add document only allows files
The add_document method for discovery only allows file objects.  It should also allow the addition of data in a string buffer as well as file objects.

### PR DESCRIPTION
**Pull request by kognate**
Before you could only add documents as files. now
the document data doesn't have to be in a file, it can be
in a string.

Fixes #140

### CODE REVIEW

**Comment by jsstylos** [comment]
Should probably clean up the parameter names to match the snake casing of the other parameters.

**Comment by kognate** [comment]
I updated those param names.

**Comment by jsstylos** [comment]
Looks like pylint is complaining about indentation now. metadata is a word, so doesn't need to be separated -- the others look good.

**Comment by jsstylos** [comment]
Looks good

**Pull request merged**
